### ISSUE TITLE
The or thing happens every where!

### ISSUE THREAD

**Issue by pouyakary** [arendelle/kai#1]
<img width="139" alt="screen shot 2015-11-07 at 11 22 44 pm" src="https://cloud.githubusercontent.com/assets/2157285/11017011/3b01785a-85a7-11e5-91d8-8cdf98f12be3.png">

How about defining the Arendelle's MEL (mathematical expression language) grammar? I'll give you the instructions

**Comment by sinabakh** [comment]
@pmkary
The "or"/"and" issue is now patched.
For Arendelle's MEL please create a new issue.

**Comment by sinabakh** [comment]
Version 0.2.12 released.
Please download the latest version.
