### ISSUE TITLE
Function's first arg problem

### ISSUE THREAD

**Issue by pouyakary** [arendelle/kai#2]
<img width="185" alt="screen shot 2015-11-07 at 11 21 39 pm" src="https://cloud.githubusercontent.com/assets/2157285/11017021/8e7eef58-85a7-11e5-8454-8f165d28c302.png">
<img width="188" alt="screen shot 2015-11-07 at 11 21 35 pm" src="https://cloud.githubusercontent.com/assets/2157285/11017026/a57a4a72-85a7-11e5-9c5e-44995c517477.png">

**Comment by sinabakh** [comment]
Version 0.2.12 released.
Please download the latest version.
